name: social_media_with_chatgpt
description: A new Flutter project.

# Script
# Launch icon: flutter pub run flutter_launcher_icons
# flutter pub run build_runner build --delete-conflicting-outputs
# flutter pub run build_runner clean
# flutter pub run easy_localization:generate --source-dir 'assets/translations' --output-dir 'lib/generated' --output-file 'translations.g.dart' --format keys
# flutter build apk

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  flutter_bloc: ^8.1.2

  # For Assets
  flutter_gen: ^5.2.0
  flutter_svg: ^2.0.0
  google_fonts: ^4.0.3
  lottie: ^2.6.0

  # For Localizations
  easy_localization: ^3.0.3

  # For Model
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1

  # For Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1

  # For Utilities
  equatable: ^2.0.5
  after_layout: ^1.2.0
  connectivity_plus: ^4.0.1
  bot_toast: ^4.0.4
  stomp_dart_client: ^0.4.4
  permission_handler: ^11.0.1
  shared_preferences: ^2.0.18
  scrollable_positioned_list: ^0.3.8
  pin_code_fields: ^8.0.1
  uuid: ^3.0.7
  emoji_picker_flutter: ^1.6.3

  # For Image
  image_picker: ^1.0.2
  file_picker: ^5.3.1
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3

  # Dynamic link
  firebase_dynamic_links: ^5.3.5
  firebase_core: ^2.15.1
  onesignal_flutter: ^5.0.3

  # For Onboarding
  introduction_screen: ^3.1.12

  #For speech to text
  google_speech: ^2.2.0
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16

  #For openai
  dart_openai: ^1.9.91
  group_list_view: ^1.1.1
  animated_text_kit: ^4.2.2
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For Builder
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0

  # For Model
  freezed: ^2.4.1

  # For Networking
  retrofit_generator: ^6.0.0+1
  device_preview: ^1.1.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
